# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebox', '0002_auto_20170813_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
