# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebox', '0004_auto_20170815_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, unique=True),
        ),
    ]
