# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pastebox', '0008_analytics_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 15, 22, 4, 53, 541434, tzinfo=utc)),
        ),
    ]
